# Generated by Django 4.2.7 on 2025-04-05 14:01

import analyzer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to=analyzer.models.video_upload_path),
        ),
        migrations.AlterField(
            model_name='video',
            name='file_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
